#! /bin/sh
#Author: Adam McKenney (adam@quitetiny.com)
#License: GNU GPLv3 (see LICENSE.md in the main directory)
#
#This is a simple script to compile Crawl on GNU/Linux
#You need the compiler 'vbnc2' to create the program
#For debian, type 'sudo apt-get install vbnc2' and you
#should get the compiler and maybe mono run-time
#The compiler is piped to more because if there is an error
#you can actually read it, also more people have 'more' than 'less'
#yeah that sounds weird...
echo Compiling...
vbnc2 -t:exe -nologo -warnaserror+ -out:Crawl Crawl.vb | more
echo Creating Windows binary
cp Crawl Crawl.exe
#-t:exe		is for a console program
#-nologo	is for a faster and nicer experience
#-warnaserror	is for making warnings treated like errors (I dont 'do' warnings)
#-out:Crawl	is for naming the program Crawl (no .exe for GNU/Linux)
#Crawl.vb	is the Visual Basic source file
echo Done!

